spring:
  datasource:
    url: jdbc:mysql://database-2.cbd3bcbn6fzf.ap-northeast-2.rds.amazonaws.com:3306/anbu?serverTimezone=Asia/Seoul
    username: admin
    password: qjawns1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-type: pkcs12
    key-store-password: 123456
    key-alias: spring
